jobs:

  - name: newrunshscript
    type: runSh
    steps:
      - IN: sample-scriptrepo
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptrepo/gitRepo/echo.sh
    on_success:
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
   
  - name: testmanifest
    type: manifest
    steps:
      - IN: img1sh
      - IN: sample-scriptrepo

 
  - name: testddcdeploy
    type: deploy
    steps:
      - IN: rc-ddccluster
      - IN: sample-scriptrepo
      
  - name: ar-release
    type: release
    steps:
      - IN: ar-version
      - IN: sample-scriptrepo 
      - TASK: managed
        bump: patch
   
