jobs:
  - name: ecs-man2
    type: manifest
    steps:
      - IN: rc-img2
      
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-man2
      - IN: rc-img1
      - IN: ecs-dopts
      - IN: ecs-params1
      - IN: ecs-img
      - IN: rc-tg1

  - name: up-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: bg-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
   
  - name: rp-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: replace  
