jobs:

  - name: newrunshscript
    type: runSh
    steps:
      - IN: sample-scriptrepo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptrepo/gitRepo/echo.sh
    on_success:
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
   
