jobs:

  - name: runshscript-pubrepo
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-scriptPubRepo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPubRepo/gitRepo/echo.sh
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
      - script: echo 'it is for on_start'
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc

  - name: runshscript-pvtrepo
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: sample-scriptPvtRepo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPvtRepo/gitRepo/echo.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc

  - name: runcliscript-pubrepo
    type: runCLI
    allowPublicAccess: false
    steps:
      - IN: sample-scriptPubRepo
      #- IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPubRepo/gitRepo/echo.sh
    on_start:
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
      - script: echo 'it is for on_start'
    on_success:      
      - script: echo 'test in on_success'
      - script: ls
      - script: echo 'it is success'
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_failure:
      - script: echo 'testing1 failure'      
      - script: pwd
      - script: echo 'OOPS on_failure :('
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    on_cancel:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc
    
  - name: runcliscript-pvtrepo
    type: runCLI
   # allowPublicAccess: true
   #   - true
    steps:
      - IN: sample-scriptPvtRepo
    #  - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPvtRepo/gitRepo/echo.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
      - NOTIFY: notify-email
      - NOTIFY: notify-hipchat
      - NOTIFY: notify-irc

  - name: testmanifest
    type: manifest
    steps:
      - IN: img1sh
     # - IN: sample-scriptrepo

 
  - name: testddcdeploy
    type: deploy
    steps:
      - IN: rc-ddccluster
      - IN: testmanifest
      #- IN: sample-scriptrepo
      
  - name: ar-release
    type: release    
    steps:
      - IN: ar-version
      #- IN: sample-scriptrepo 
      - TASK: managed
        bump: patch
   
