jobs:
  - name: rc-man1
    type: manifest
    steps:
      - IN: rc-img1
      - IN: rc-tg1

  - name: tpdeploy-27octrc
    type: deploy
    steps:
      - IN: rc-man1
      - IN: rc-img2
      - IN: testscale
      - IN: rc-tripubcluster
