jobs:
  - name: ecs-man2
    type: manifest
    steps:
      - IN: rc-img2
      
  - name: ecs-man1
    type: manifest
    steps:
     ## - IN: ecs-man2
      ##- IN: rc-img1
      - IN: ecs-dopts
      - IN: ecs-params1
      ##- IN: ecs-scale2
      - IN: ecs-img
      - IN: rc-tg1

  - name: up-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: bg-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
   
  - name: rp-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: replace  
        
  - name: ecs-lbmani80
    type: manifest
    steps:
      - IN: lb-myapp3ecs
      - IN: lb-ecsdopts80
      
  - name: ecs-lbmani3000
    type: manifest
    steps:
      - IN: lb-myapp2ecs
      #- IN: lb-ecsdopts3000
      
  - name: lb-ecsdeploy80
    type: deploy
    steps:
      - IN: ecs-lbmani80
      - IN: lb-ecscluster
      - IN: ecs-lb80
        applyTo:
          - manifest: ecs-lbmani80
            image: lb-myapp3ecs
            port: 8080:80
      - TASK: managed
        deployMethod: replace
     
  - name: lb-ecsdeploy3000rp
    type: deploy
    steps:
      - IN: ecs-lbmani3000
      - IN: lb-ecscluster
      - IN: ecs-lb3000
        applyTo:
          - manifest: ecs-lbmani3000
            image: lb-myapp2ecs
            port: 3000
      - TASK: managed
        deployMethod: replace
