jobs:
  #- name: gke-man2
   # type: manifest
    #steps:
     # - IN: rc-img2
      
  - name: gke-man1
    type: manifest
    steps:
      ##- IN: ecs-man2
      - IN: gke-img
      - IN: rc-img1
      - IN: gke-dopts     
      - IN: gke-params1
     # - IN: gke-scale2
      - IN: gke-tg1

  - name: up-gke1
    type: deploy
    steps:
      - IN: gke-man1
      #-IN: gke-scale3 #check override
      - IN: gkecluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: bg-gke1
    type: deploy
    steps:
      - IN: gke-man1
      #-IN: gke-scale3 #check override
      - IN: gkecluster
   
  - name: rp-gke1
    type: deploy
    steps:
      - IN: gke-man1
      #-IN: gke-scale3 #check override
      - IN: gkecluster
      - TASK: managed
        deployMethod: replace  
        
 
