triggers:
   - name: ar-tg1
     type: trigger
     version:
       counter: 0
       
   - name: ar-tg2
     type: trigger
     version:
       counter: 0
       
   - name: ar-tg3
     type: trigger
     version:
       counter: 0

   - name: ar-release1tr
     type: release
     steps:
       - IN: ar-version
         #versionName: testrelease
     #  - IN: ar-inrunSh
