triggers:
   - name: extdopt-tg1
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg2
     type: trigger
     version:
       counter: 1
       
   - name: extdopt-tg3
     type: trigger
     version:
       counter: 1
       
   - name: extdopt-tg4
     type: trigger
     version:
       counter: 1
       
   - name: extdopt-tg5
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg6
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg7
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg8
     type: trigger
     version:
       counter: 0
       
   - name: extdopt-tg9
     type: trigger
     version:
       counter: 0
