jobs:
 # - name: gke-man2
  #  type: manifest
  #  steps:
     # - IN: rc-img2
      
  - name: tp-man1
    type: manifest
    steps:
    #  #- IN: gke-man2
      - IN: tp-img
   #   #- IN: rc-img1
      - IN: tp-dopts     
      - IN: tp-params1
     # - IN: gke-scale2
      - IN: tp-tg1

  - name: up-tp
    type: deploy
    steps:
      - IN: tp-man1
    ##  - IN: gke-scale3 #check override
      - IN: tripubcluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: bg-tp
    type: deploy
    steps:
      - IN: tp-man1
    ##  - IN: gke-scale3 #check override
      - IN: tripubcluster
   
  - name: rp-tp
    type: deploy
    steps:
      - IN: tp-man1
    ##  - IN: gke-scale3 #check override
      - IN: tripubcluster
      - TASK: managed
        deployMethod: replace  
        
 
