jobs:
  - name: dep-man1test
    type: manifest
    steps:
      - IN: rc-img1
      - IN: dep-dopts
      - IN: rc-tg1

  - name: dep-ddcdeploytest
    type: deploy
    steps:
      - IN: dep-man1test
      - IN: rc-ddccluster
    on_start:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'start'
    on_success:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'success'
    on_failure:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'failure'
      
  - name: dep-dcldeploytest
    type: deploy
    steps:
      - IN: dep-man1test
      - IN: rc-dclcluster
    on_start:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_success:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_failure:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      
  - name: dep-ecsdeploytest
    type: deploy
    steps:
      - IN: dep-man1test
      - IN: rc-ecscluster
    on_start:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_success:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_failure:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest

  - name: dep-gkedeploytest
    type: deploy
    steps:
      - IN: dep-man1test
      - IN: rc-gkecluster
      - TASK: managed
        deployMethod: upgrade
    on_start:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_success:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
    on_failure:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      
  - name: dep-tpdeploytest
    type: deploy
    steps:
      - IN: dep-man1test
      - IN: rc-tripubcluster
      - TASK: managed
        deployMethod: replace
    on_start:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'start'
    on_success:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'success'
    on_failure:
      - NOTIFY: dep-slacktest
      - NOTIFY: dep-emailtest
      - script: echo 'fail'
      
  - name: alldeploy-release
    type: release
    steps:
      - IN: depall-version
        #versionName: testrelease
      - IN: dep-ddcdeploytest
     # - IN: dep-ecsdeploytest
      - IN: dep-dcldeploytest
      - IN: dep-gkedeploytest
      - IN: dep-tpdeploytest
  #    - IN: timedailyprod-release
      - TASK: managed
        bump: rc
    flags:
      - deployall-notification
      
