jobs:

  - name: runshscript-pubrepo
    type: runSh
   # allowPublicAccess: true
    steps:
      - IN: sample-scriptPubRepo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPubRepo/gitRepo/echo.sh
    on_success:
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'

  - name: runshscript-pvtrepo
    type: runSh
    #allowPublicAccess: 
      #- true
    steps:
      - IN: sample-scriptPvtRepo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPvtRepo/gitRepo/echo.sh

  - name: runcliscript-pubrepo
    type: runCLI
 #   allowPublicAccess: true
    steps:
      - IN: sample-scriptPubRepo
      #- IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPubRepo/gitRepo/echo.sh
    on_success:
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
    
  - name: runcliscript-pvtrepo
    type: runCLI
   # allowPublicAccess: true
   #   - true
    steps:
      - IN: sample-scriptPvtRepo
    #  - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/sample-scriptPvtRepo/gitRepo/echo.sh

  - name: testmanifest
    type: manifest
    steps:
      - IN: img1sh
     # - IN: sample-scriptrepo

 
  - name: testddcdeploy
    type: deploy
    steps:
      - IN: rc-ddccluster
      - IN: testmanifest
      #- IN: sample-scriptrepo
      
  - name: ar-release
    type: release    
    steps:
      - IN: ar-version
      #- IN: sample-scriptrepo 
      - TASK: managed
        bump: patch
   
