jobs:
  - name: rc-man1
    type: manifest
    steps:
      - IN: rc-img1
      - IN: rc-tg1

  - name: ci-man2
    type: manifest
    steps:
      - IN: ci-img1et
      - IN: ci-img2et

  - name: tpdeploy-27octrc
    type: deploy
    steps:
      - IN: rc-man1
      - IN: rc-img2
      - IN: rc-tripubcluster
