jobs:

  - name: inrunshtest
    type: runSh
    steps:
      - IN: myscript-repo
      - IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/myscript-repo/gitRepo/echo.sh
    on_success:
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
   
