jobs:
      
#MANIFESTS
      
  - name: extdopt-manifest1
    type: manifest
    steps:
      - IN: rc-img1
       # versionNumber: 100
      - IN: extdopt-tg1
    flags:
      - man_extdopts
      
  - name: extdopt-manifest2multiimg
    type: manifest
    steps:
      - IN: rc-image6entrypoint
      - IN: rc-image7workingdir
      - IN: extdoptecs-dopts5
        applyTo:
          - rc-image6entrypoint
      - IN: extdopt-tg2
      
  - name: extdopt-manifest3entrypt
    type: manifest
    steps:
      - IN: rc-image6entrypoint
      - IN: extdopt-tg3
      
  - name: extdopt-manifest4driftking
    type: manifest
    steps:
      - IN: rc-image7workingdir
      - IN: extdopt-tg4
      
#DEPLOYMENTS 

  - name: extdopt-ecsdeploywdir
    type: deploy
    steps:
      - IN: extdopt-manifest2multiimg
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdoptecs-dopts4
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-tpdeployept #First deploy something in tripub n copy conatiner name n give in fltp-dopts2 resource
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopttp-dopts2
      - IN: rc-tripubcluster
      - TASK: managed
        deployMethod: upgrade

  - name: extdopt-tpdeploywdir
    type: deploy
    steps:
      - IN: extdopt-manifest4driftking
      - IN: extdopttp-dopts1
      - IN: rc-tripubcluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-gkedeploywdir
    type: deploy
    steps:
      - IN: extdopt-manifest4driftking
      - IN: extdoptgke-dopts3
      - IN: rc-gkecluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: extdopt-ddcdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdoptddc-dopts6
      - IN: rc-ddccluster
        
  - name: extdopt-ddcdeploywdir #First deploy something in ddc n copy conatiner name n give in extdopt-ddc2 resource
    type: deploy
    steps:
      - IN: extdopt-manifest4driftking
      - IN: extdoptddc-dopts7
      - IN: rc-ddccluster
