jobs:
  - name: ecs-man2
    type: manifest
    steps:
      - IN: rc-img2
      
  - name: ecs-man1
    type: manifest
    steps:
      ##- IN: ecs-man2
      - IN: rc-img1
      - IN: ecs-dopts
      - IN: ecs-params1
        applyTo:
          - ecs-img
      ##- IN: ecs-scale2
      - IN: ecs-img
      - IN: rc-tg1

  - name: up-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: bg-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
   
  - name: rp-ecs
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecscluster
      - TASK: managed
        deployMethod: replace  
        
  - name: ecs-lbmani80
    type: manifest
    steps:
      - IN: lb-myapp3ecs
      - IN: lb-ecsdopts80
      
  - name: ecs-lbmani3000
    type: manifest
    steps:
      - IN: lb-myapp2ecs
      - IN: lb-ecsdopts3000
      
  - name: lb-ecsdeploy80
    type: deploy
    steps:
      - IN: ecs-lbmani80
      - IN: lb-ecscluster
      - IN: ecs-lb80
        applyTo:
          - manifest: ecs-lbmani80
            image: lb-myapp3ecs
            port: 8080:80
      - TASK: managed
        deployMethod: replace
     
  - name: lb-ecsdeploy3000rp
    type: deploy
    steps:
      - IN: ecs-lbmani3000
      - IN: lb-ecscluster
      - IN: ecs-lb3000
        applyTo:
          - manifest: ecs-lbmani3000
            image: lb-myapp2ecs
            port: 3000
      - TASK: managed
        deployMethod: replace
      
  - name: extdopt-manifest2
    type: manifest
    steps:
      - IN: rc-image7workingdir
      - IN: extdopt-ecs2     

  - name: extdopt-manifest3entrypt
    type: manifest
    steps:
      - IN: rc-image6entrypoint
            
  - name: upextdopt-ecsdeploywdir1
    type: deploy
    steps:
      - IN: extdopt-manifest2
      - IN: ecs-scale2
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: upextdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopt-ecs1
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: rpextdopt-ecsdeploywdir1
    type: deploy
    steps:
      - IN: extdopt-manifest2
      - IN: ecs-scale2
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: replace
        
  - name: rpextdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopt-ecs1
      - IN: rc-ecscluster
      - TASK: managed
        deployMethod: replace
        
  - name: bgextdopt-ecsdeploywdir1
    type: deploy
    steps:
      - IN: extdopt-manifest2
      - IN: ecs-scale2
      - IN: rc-ecscluster
        
  - name: bgextdopt-ecsdeployept
    type: deploy
    steps:
      - IN: extdopt-manifest3entrypt
      - IN: extdopt-ecs1
      - IN: rc-ecscluster
        
